# DenseNet Configuration for torchvision models
model:
  name: "densenet121"  # Options: densenet121, densenet169, densenet201, densenet161
  num_classes: 1000
  pretrained: true  # Use ImageNet pre-trained weights

# Training/Inference settings
inference:
  device: "cuda"  # or "cpu"
  batch_size: 1
  image_size: [224, 224]
  mean: [0.485, 0.456, 0.406]  # ImageNet normalization
  std: [0.229, 0.224, 0.225]   # ImageNet normalization

# Model weights path (if loading custom weights)
weights:
  path: "custom_densenet_weights.pth"
  load_pretrained: false  # Set to true to load custom weights instead of torchvision pretrained 