# DenseNet Configuration for custom implementation
model:
  name: "DenseNet"
  num_classes: 1000
  growth_rate: 32
  block_config: [6, 12, 24, 16]  # DenseNet-121 configuration
  num_init_features: 64
  drop_rate: 0.0

# Training/Inference settings
inference:
  device: "cuda"  # or "cpu"
  batch_size: 1
  image_size: [224, 224]
  mean: [0.485, 0.456, 0.406]  # ImageNet normalization
  std: [0.229, 0.224, 0.225]   # ImageNet normalization

# Model weights path (if loading pre-trained)
weights:
  path: "weights/densenet121_pretrained.pth"
  load_pretrained: false  # Set to true to load pre-trained weights 